### ISSUE TITLE
我的问题与“似乎内存不足&有模块导入失败，原因未知”应该是一样的，但是怎么更换mpy-cross的版本？

### ISSUE THREAD

**Issue by INPEIU** [tljk/youdao_wordbook#3]
Traceback (most recent call last):
  File "boot.py", line 1, in <module>
  File "main.py", line 19, in <module>
MemoryError: memory allocation failed, allocating 656 bytes
Traceback (most recent call last):
  File "main.py", line 19, in <module>
ImportError: can't import name EPD_2in13_V3
MicroPython v1.17 on 2021-09-22; ESP32 module with ESP32
Type "help()" for more information.

我的问题与“似乎内存不足&有模块导入失败，原因未知”   https://github.com/tljk/youdao_wordbook/issues/2
应该是一样的，但是怎么更换mpy-cross的版本？
我已经下载了micropython1.17的发行版压缩包
win11系统，64位，
板子是在仓库内的链接购买的

**Comment by tljk** [comment]
`pip install mpy-cross==1.18`
or manually
[https://gitlab.com/alelec/mpy_cross/-/pipelines?scope=tags&page=1(url)

**Comment by INPEIU** [comment]
好吧，现在是这个
Traceback (most recent call last):
  File "boot.py", line 1, in <module>
  File "F:\ϵͳĬ��\����\youdao_wordbook-master\src\main.py", line 18, in <module>
ImportError: no module named 'urequests'
MicroPython v1.17 on 2021-09-22; ESP32 module with ESP32
Type "help()" for more information.

**Comment by INPEIU** [comment]
感谢！！！！！！！！！！成功啦！！！
